# Nome do workflow que aparecerá na aba Actions do GitHub
name: Build, Push, and Deploy Docker Image

# Define o gatilho: esse workflow será executado quando houver um push na branch "main"
on:
  push:
    branches:
      - main

jobs:
  # Primeiro job: build da imagem e push para o DockerHub
  build-and-push:
    runs-on: ubuntu-latest  # Define o sistema operacional da máquina que executa o job

    steps:
      # Clona o repositório no ambiente de execução (runner)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o Docker Buildx (recurso avançado de build do Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Faz login no DockerHub com usuário e token armazenados em secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Constrói a imagem Docker e faz o push para o DockerHub
      - name: Build and push Docker image
        run: |
          # Constrói a imagem com a tag do commit atual (github.sha)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ github.sha }} .
          # Envia (push) a imagem para o DockerHub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-crud:${{ github.sha }}
